language: php

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
    - php: 5.5
      env: COMPOSER_FLAGS="--prefer-lowest"

install: composer update $COMPOSER_FLAGS --prefer-dist
